#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

require "sqlite3"

db = SQLite3::Database.new "cards.db"
query = db.prepare "SELECT * FROM cards WHERE name=?"

ARGF.each do |card|
  begin
    puts query.execute(card.chomp).next.join("|")
  rescue
    puts "Could not find #{card}"
    exit
  end
end
