#!/usr/bin/env ruby

$LOAD_PATH.unshift(File.dirname(__FILE__))

require "sqlite3"

db = SQLite3::Database.new ENV["CARD_DB_PATH"]
query = db.prepare "SELECT * FROM cards WHERE name=?"

ARGF.each do |card|
  begin
    puts query.execute(card.gsub(/\s*$/, "")).next.join("|").gsub("\n", " ")
  rescue
    puts "Could not find #{card.inspect}"
    exit
  end
end
