#!/usr/bin/env ruby

html = <<-HTML
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="styles.css">
    <style>
      html, body {
        background-color: #555;
        margin: 0;
      }

      .wrapper {
        margin: 0 auto;
        padding: 50px 10px;
        width: 1310px;
      }

      img {
        width: 140px;
        margin: 10px;
      }
      img:hover {
        -webkit-transform: scale(1.5);
      }
    </style>
  </head>
  <body>
    <div class="wrapper">
HTML

def make_img(card)
  # TODO: encode card for URL
  safe_name = card.chomp
  "<img src=\"http://mtgimage.com/card/#{safe_name}.jpg\">\n"
end

ARGF.each do |card|
  html += make_img(card) if card.chomp.length > 0
end

html += "    </div>\n  </body>\n</html>"

puts html
