#!/usr/bin/env ruby

require "open-uri"

html = <<-HTML
<!doctype html>
<html>
  <head>
    <link rel="stylesheet" href="styles.css">
    <style>
      html, body {
        background-color: #555;
        margin: 0;
      }

      .wrapper {
        margin: 0 auto;
        padding: 50px 10px;
        width: 1310px;
      }

      img {
        width: 220px;
        margin: 25px 50px;
      }
    </style>
  </head>
  <body>
    <div class="wrapper">
HTML

def make_img(card)
  "<img src=\"http://mtgimage.com/card/#{URI::encode(card.chomp)}.jpg\" width=220px height=312px>\n"
end

ARGF.each do |card|
  html += make_img(card) if card.chomp.length > 0
end

puts html + "    </div>\n  </body>\n</html>"
